apiVersion: apps/v1
kind: Deployment
metadata:
  name: typescript-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typescript-app
  template:
    metadata:
      labels:
        app: typescript-app
    spec:
      containers:
      - name: typescript-ap
        image: typescript-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "<your-access-key>"
        - name: AWS_SECRET_ACCESS_KEY
          value: "<your-secret-key>"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
---
apiVersion: v1
kind: Service
metadata:
  name: typescript-service
spec:
  selector:
    app: typescript-app
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
